### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by failster** [KewaiiGamer/LanServerExtended#1]
When people try to connect to the world it says "Mod rejections [FMLMod:lse{1.1}]"
Any way I can fix this?

**Comment by KewaiiGamer** [comment]
I am currently really busy and I won't be making much updates on this mod. Meanwhile you can fix it by making everyone else who is trying to join your server install LanServerExtended

**Comment by KewaiiGamer** [comment]
Issue has been fixed on 1.2.0. Closing the issue!
